name: actions
on: [push]
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn compile
      - uses: actions/upload-artifact@v2
        with:
          name: game2048compiled
          path: ./target/*
  test:
    name: test
    runs-on: self-hosted
    needs: build
    steps:
      - name: test
        run: mvn test
        working-directory: ./src
  package:
    name: package
    runs-on: self-hosted
    needs: build
    steps:
      - name: package
        run: mvn package
        working-directory: ./src
  deploy:
    name: deploy
    runs-on: self-hosted
    needs: package
    steps:
      - name: deploy_test
        run: |
          docker rm --force tomcat
          docker image rm --force game2048
          echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
          docker run --rm -d --name tomcat -p 8080:8080 game2048
      - name: deploy_stop
        run: |
          docker rm --force tomcat
          docker image rm --force game2048